name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: 3.110.40.245
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "."
          target: "~/octabyte-python-app"

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 3.110.40.245
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd ~/octabyte-python-app
            docker stop octa || true
            docker rm octa || true
            docker build -t octabyte-python-app .
            docker run -d -p 5000:5000 --name octa octabyte-python-app
